# Ultralytics YOLO 🚀, AGPL-3.0 license
# Pre-commit hooks. For more information see https://github.com/pre-commit/pre-commit-hooks/blob/main/README.md

- id: capitalize-comments
  name: 'Capitalize standalone inline comments'
  entry: hooks/capitalize_comments.py
  language: python
  language_version: python3  # Ensure Python 3 is specified
  types: [python]
