# Ultralytics YOLO 🚀, AGPL-3.0 license
# Pre-commit hooks. For more information see https://github.com/pre-commit/pre-commit-hooks/blob/main/README.md

- id: capitalize-comments
  name: Capitalize standalone inline comments
  description: This hook capitalizes the first letter in standalone inline comments.
  entry: capitalize_comments.py
  language: python
  types: [python]
