# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license

blank_issues_enabled: true
contact_links:
  - name: 📄 README
    url: https://github.com/ultralytics/pre-commit#readme
    about: Hook definitions and usage for the Ultralytics pre-commit hooks
  - name: 💬 Forum
    url: https://community.ultralytics.com/
    about: Ask on Ultralytics Community Forum
  - name: 🎧 Discord
    url: https://ultralytics.com/discord
    about: Ask on Ultralytics Discord
  - name: ⌨️ Reddit
    url: https://reddit.com/r/ultralytics
    about: Ask on Ultralytics Subreddit
